services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  backend:
    build:
      context: ./chatter-backend
      dockerfile: Dockerfile
    env_file: ./chatter-backend/docker.env
    ports:
      - '3001:3001'
    volumes:
      - ./chatter-backend:/app
      - /app/node_modules
volumes:
  data:
